version: '2'

services:
  orderer.VotingProxy.com:
    container_name: orderer.VotingProxy.com
    image: hyperledger/fabric-orderer:x86_64-1.0.4
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      - GRPC_TRACE=all=true
      - GRPC_VERBOSITY=debug
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
     - ../crypto:/etc/hyperledger/configtx:ro
     - ../crypto/crypto-config/ordererOrganizations/VotingProxy.com/orderers/orderer.VotingProxy.com/:/etc/hyperledger/orderer:ro
    ports:
      - 7050:7050

  CustodianCA:
    image: hyperledger/fabric-ca:x86_64-1.0.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.Custodian.VotingProxy.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/58f8941338b664dd91aa7b1415bb66247990a46e86d5fe733c240d1155c5c60b_sk -b admin:adminpw --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.Custodian.VotingProxy.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/58f8941338b664dd91aa7b1415bb66247990a46e86d5fe733c240d1155c5c60b_sk -d'
    volumes:
      - ../crypto/crypto-config/peerOrganizations/Custodian.VotingProxy.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    container_name: CustodianCA

  peer0.Custodian.VotingProxy.com:
    container_name: peer0.Custodian.VotingProxy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.Custodian.VotingProxy.com
      - CORE_PEER_ADDRESS=peer0.Custodian.VotingProxy.com:7051
      - CORE_PEER_LOCALMSPID=CustodianMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto/crypto-config/peerOrganizations/Custodian.VotingProxy.com/peers/peer0.Custodian.VotingProxy.com/:/etc/hyperledger/peer:ro
      - ../:/opt/gopath/src/github.com/hyperledger/fabric/peer:rw
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.VotingProxy.com

  MorganStanleyCA:
    image: hyperledger/fabric-ca:x86_64-1.0.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "7064:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.MorganStanley.VotingProxy.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2742a43d74db8b893d20bd293c4cf4972ec7471f0a19d9e82ba6084ee6e36bc2_sk -b admin:adminpw --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.MorganStanley.VotingProxy.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/2742a43d74db8b893d20bd293c4cf4972ec7471f0a19d9e82ba6084ee6e36bc2_sk -d'
    volumes:
      - ../crypto/crypto-config/peerOrganizations/MorganStanley.VotingProxy.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    container_name: MorganStanleyCA

  peer0.MorganStanley.VotingProxy.com:
    container_name: peer0.MorganStanley.VotingProxy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.MorganStanley.VotingProxy.com
      - CORE_PEER_ADDRESS=peer0.MorganStanley.VotingProxy.com:7051
      - CORE_PEER_LOCALMSPID=MorganStanleyMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto/crypto-config/peerOrganizations/MorganStanley.VotingProxy.com/peers/peer0.MorganStanley.VotingProxy.com/:/etc/hyperledger/peer:ro
      - ../:/opt/gopath/src/github.com/hyperledger/fabric/peer:rw
    ports:
      - 7061:7051
      - 7063:7053
    depends_on:
      - orderer.VotingProxy.com

  GoldmanSacksCA:
    image: hyperledger/fabric-ca:x86_64-1.0.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "7074:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.GoldmanSacks.VotingProxy.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/1d67efded5bccc34d52cf414d85badd2b12c91d13f71d386bf237de8d4b7c499_sk -b admin:adminpw --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.GoldmanSacks.VotingProxy.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/1d67efded5bccc34d52cf414d85badd2b12c91d13f71d386bf237de8d4b7c499_sk -d'
    volumes:
      - ../crypto/crypto-config/peerOrganizations/GoldmanSacks.VotingProxy.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    container_name: GoldmanSacksCA

  peer0.GoldmanSacks.VotingProxy.com:
    container_name: peer0.GoldmanSacks.VotingProxy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.GoldmanSacks.VotingProxy.com
      - CORE_PEER_ADDRESS=peer0.GoldmanSacks.VotingProxy.com:7051
      - CORE_PEER_LOCALMSPID=GoldmanSacksMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto/crypto-config/peerOrganizations/GoldmanSacks.VotingProxy.com/peers/peer0.GoldmanSacks.VotingProxy.com/:/etc/hyperledger/peer:ro
      - ../:/opt/gopath/src/github.com/hyperledger/fabric/peer:rw
    ports:
      - 7071:7051
      - 7073:7053
    depends_on:
      - orderer.VotingProxy.com

  JPMorganCA:
    image: hyperledger/fabric-ca:x86_64-1.0.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "7084:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.JPMorgan.VotingProxy.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/28afc1af1bc0c4adea43568bb972ce535cfeac65526e7897c9d8ebd0cbfff6f8_sk -b admin:adminpw --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.JPMorgan.VotingProxy.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/28afc1af1bc0c4adea43568bb972ce535cfeac65526e7897c9d8ebd0cbfff6f8_sk -d'
    volumes:
      - ../crypto/crypto-config/peerOrganizations/JPMorgan.VotingProxy.com/ca/:/etc/hyperledger/fabric-ca-server-config:ro
    container_name: JPMorganCA

  peer0.JPMorgan.VotingProxy.com:
    container_name: peer0.JPMorgan.VotingProxy.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.JPMorgan.VotingProxy.com
      - CORE_PEER_ADDRESS=peer0.JPMorgan.VotingProxy.com:7051
      - CORE_PEER_LOCALMSPID=JPMorganMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto/crypto-config/peerOrganizations/JPMorgan.VotingProxy.com/peers/peer0.JPMorgan.VotingProxy.com/:/etc/hyperledger/peer:ro
      - ../:/opt/gopath/src/github.com/hyperledger/fabric/peer:rw
    ports:
      - 7081:7051
      - 7083:7053
    depends_on:
      - orderer.VotingProxy.com

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.0.4 
    tty: true
    command: /bin/bash -c 'sleep 1000000'
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    environment:
      - GOPATH=/opt/gopath
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_ID=cli
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
    ports:
      - 7091:7051
      - 7093:7053
    volumes:
      - ../:/opt/gopath/src/github.com/hyperledger/fabric/peer:rw
      - ../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/chaincode:rw
      
  ccenv:
    image: hyperledger/fabric-ccenv:x86_64-1.0.4
      